server:
  listen: "127.0.0.1:8181"
  read_timeout_seconds: 15
  write_timeout_seconds: 30
  shutdown_timeout_seconds: 20

storage:
  postgres_dsn: "postgres://votechain:change-me@127.0.0.1:5432/votechain_ingest?sslmode=disable"
  max_conns: 20
  min_conns: 2

security:
  bearer_token: "replace-with-long-random-token"
  enable_bearer_auth: true
  enable_ip_allow_list: true
  trusted_cidrs:
    - "127.0.0.1/32"
    - "10.0.0.0/8"
  max_body_bytes: 67108864
  require_machine_key_id: true
  enforce_secure_transport: false

machine_registry:
  path: "./examples/machine-registry.yaml"

logging:
  service: "votechain-ingest"
  version: "0.1.0"
  commit: "dev"
  region: "central-ingest"
